INSERT INTO Usuario(email, password, rol, activo) VALUES('test@unlam.edu.ar', 'test', 'ADMIN', true);

INSERT INTO Pregunta (id, descripcion, fase, nivel)
VALUES
    (1, '¿Cuándo fue fundada oficialmente la ciudad de Ushuaia?', 1, 1),
    (2, '¿Quién fue el explorador europeo que navegó por el estrecho de Magallanes en 1520?', 1, 1),
    (3, '¿Qué tratado definió los límites entre Argentina y Chile en Tierra del Fuego en 1881?', 1, 1),
    (4, '¿Cuál es la isla más grande de Tierra del Fuego?', 2, 1),
    (5, '¿Cuál fue la principal actividad económica en Tierra del Fuego durante la colonización?', 2, 1),
    (6, '¿Qué acontecimiento llevó a la construcción del presidio de Ushuaia a principios del siglo XX?', 2, 1),
    (7, '¿Cuál es el nombre tradicional de los habitantes originarios de Tierra del Fuego, conocidos por sus habilidades en la navegación en canoas?', 3, 1),
    (8, '¿Qué expedición científica francesa realizó importantes estudios en Tierra del Fuego en el siglo XIX?', 3, 1),
    (9, '¿Cuál de los siguientes pueblos originarios habitaba Tierra del Fuego antes de la llegada de los europeos?', 3, 1),
    (10, '¿En qué año se fundó la provincia de Santa Cruz en Argentina?', 1, 2),
    (11, '¿Quién fue el explorador que realizó expediciones importantes en la región de Santa Cruz durante el siglo XIX?', 1, 2),
    (12, '¿Cuál es el principal río que atraviesa la provincia de Santa Cruz?', 1, 2),
    (13, '¿Qué evento histórico en Santa Cruz está asociado con la expedición del HMS Beagle?', 2, 2),
    (14, '¿Cuál es el parque nacional ubicado en la provincia de Santa Cruz que alberga al glaciar más famoso de la región?', 2, 2),
    (15, '¿Cuál fue el conflicto bélico que involucró a la base militar británica en la isla Soledad, cercana a las costas de Santa Cruz, en 1982?', 2, 2),
    (16, '¿Cuál es el nombre del famoso lago ubicado en la provincia de Santa Cruz, conocido por su color turquesa?', 3, 2),
    (17, '¿Cuál de los siguientes pueblos originarios habitaba la región de Santa Cruz antes de la llegada de los europeos?', 3, 2),
    (18, '¿Qué actividad económica fue clave para el desarrollo de la región de Santa Cruz a finales del siglo XIX y principios del XX?', 3, 2);


INSERT INTO Respuesta (id, descripcion, esCorrecta, id_pregunta)
VALUES
    (1, '1920', 0, 1),
    (2, '1901', 0, 1),
    (3, '1884', 1, 1),
    (4, '1852', 0, 1),
    (5, 'Hernando de Soto', 0, 2),
    (6, 'Cristóbal Colón', 0, 2),
    (7, 'Juan de Garay', 0, 2),
    (8, 'Fernando de Magallanes', 1, 2),
    (9, 'Tratado de Límites', 1, 3),
    (10, 'Tratado de Río de Janeiro', 0, 3),
    (11, 'Tratado de Paz y Amistad', 0, 3),
    (12, 'Tratado de Tordesillas', 0, 3),
    (13, 'Isla Hoste', 0, 4),
    (14, 'Isla Navarino', 0, 4),
    (15, 'Isla Grande', 1, 4),
    (16, 'Isla Picton', 0, 4),
    (17, 'Ganadería ovina', 1, 5),
    (18, 'Pesca', 0, 5),
    (19, 'Minería', 0, 5),
    (20, 'Agricultura', 0, 5),
    (21, 'Conflicto con los selk''nam', 1, 6),
    (22, 'Fiebre del oro', 0, 6),
    (23, 'Descubrimiento de petróleo', 0, 6),
    (24, 'Guerra con Chile', 0, 6),
    (25, 'Yamana (Yámana)', 1, 7),
    (26, 'Mapuche', 0, 7),
    (27, 'Qulla', 0, 7),
    (28, 'Selk''nam', 0, 7),
    (29, ' Expedición La Romanche', 0, 8),
    (30, 'Expedición Malaspina', 0, 8),
    (31, 'Expedición Nassau', 0, 8),
    (32, 'Expedición Beagle', 1, 8),
    (33, 'Incas', 0, 9),
    (34, 'Selk''nam', 1, 9),
    (35, 'Aztecas', 0, 9),
    (36, 'Mapuches', 0, 9),
    (37, '1875', 0, 10),
    (38, '1878', 1, 10),
    (39, '1882', 0, 10),
    (40, '1890', 0, 10),
    (41, 'Francisco Moreno', 1, 11),
    (42, 'Juan de Garay', 0, 11),
    (43, 'Hernando de Magallanes', 0, 11),
    (44, 'Robert FitzRoy', 0, 11),
    (45, 'Deseado', 0, 12),
    (46, 'Santa Cruz', 1, 12),
    (47, 'Gallegos', 0, 12),
    (48, 'Paraná', 0, 12),
    (49, 'Descubrimiento de petróleo', 0, 13),
    (50, 'Encuentro con los tehuelches', 1, 13),
    (51, 'Llegada de los colonos galeses', 0, 13),
    (52, 'Fundación de Río Gallegos', 0, 13),
    (53, 'Parque Nacional Nahuel Huapi', 0, 14),
    (54, 'Parque Nacional Lanín', 0, 14),
    (55, 'Parque Nacional Los Glaciares', 1, 14),
    (56, 'Parque Nacional Tierra del Fuego', 0, 14),
    (57, 'Guerra del Pacífico', 0, 15),
    (58, 'Guerra de las Malvinas', 1, 15),
    (59, 'Guerra del Acre', 0, 15),
    (60, 'Guerra del Chaco', 0, 15),
    (61, 'Lago Nahuel Huapi', 0, 16),
    (62, 'Lago Argentino', 0, 16),
    (63, 'Lago Viedma', 1, 16),
    (64, 'Lago Buenos Aires', 0, 16),
    (65, 'Mapuches', 0, 17),
    (66, 'Selk''nam', 0, 17),
    (67, 'Onas', 0, 17),
    (68, 'Aonikenk (Tehuelches)', 1, 17),
    (69, 'Pesca', 0, 18),
    (70, 'Minería', 0, 18),
    (71, 'Ganadería', 1, 18),
    (72, 'Agricultura', 0, 18);